### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'request'

### ISSUE THREAD

**Issue by rofacurion** [0x9900/FT8Commander#12]
Windows Version throws error "AttributeError: module 'urllib' has no attribute 'request'"

I changed my local copy of _dxentity.py to import urllib.request at line 14

#add import urllib.request to fix "AttributeError: module 'urllib' has no attribute 'request'"
import urllib.request

**Comment by 0x9900** [comment]
This is a bug in the Python IDE. 
Run the program using either the command terminal or the power shell. 

![Screenshot_win10-2_2024-01-27_18_36_47](https://github.com/0x9900/FT8Commander/assets/2075356/7cae9d43-ae55-4a54-85e4-c574da747911)
