### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor in plugins\base.py", line 76, in __new__     tsize = os.get_terminal_size()

### ISSUE THREAD

**Issue by rofacurion** [0x9900/FT8Commander#13]
This is the error that stopped me when I was porting over to windows in December.
I am using Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32

I am getting the following error when I hit the get_terminal_size statement in base.py.

= RESTART: C:\FT8Commander-fred-windows\ft8ctrl.py
21:34:38 - INFO    121:dbutils  - Database: C:\Users\mjpat\ft8ctl.sql
21:34:38 - ERROR    75:_dxentity - DXEntity cache not found or expired
21:34:38 - INFO     86:_dxentity - Download https://www.country-files.com/cty/cty.plist
21:34:41 - INFO     93:_dxentity - Create cty cache: C:\Users\mjpat\.local\cty
21:38:20 - INFO    155:dbutils  - Datebase Insert thread started
21:38:20 - INFO    199:ft8ctrl  - Call selector: DXCC100, POTA, Any
21:38:20 - INFO    235:dbutils  - Purge thread started (retry_time 15 minutes)
Traceback (most recent call last):
  File "C:\FT8Commander-fred-windows\ft8ctrl.py", line 293, in <module>
    main()
  File "C:\FT8Commander-fred-windows\ft8ctrl.py", line 282, in main
    call_select = LoadPlugins(config.call_selector)
  File "C:\FT8Commander-fred-windows\ft8ctrl.py", line 213, in __init__
    self.call_select.append(klass())
  File "C:\FT8Commander-fred-windows\plugins\special.py", line 19, in __init__
    super().__init__()
  File "C:\FT8Commander-fred-windows\plugins\base.py", line 109, in __init__
    self.blacklist = BlackList()
  File "C:\FT8Commander-fred-windows\plugins\base.py", line 76, in __new__
    tsize = os.get_terminal_size()
OSError: [Errno 9] Bad file descriptor

I tried the following but did not resolve the problem.
#make changes to address runtime error
#    tsize = os.get_terminal_size()
    tsize = shutil.get_terminal_size()
    width = tsize.columns - 50
    _bl = ', '.join(c for c in cls.blacklist)[:width]
    _bl = _bl[:_bl.rindex(',')]
    cls.log.info("BlackList: %s...", _bl)

Not sure what's causing the error.

**Comment by 0x9900** [comment]
You got this issue because you were running the program with the IDE.
The issue has been fixed.
