### ISSUE TITLE
Call selector not found: "POTA"

### ISSUE THREAD

**Issue by rofacurion** [0x9900/FT8Commander#16]
c:\FT8Commander-fred-windows>python ft8ctrl.py
22:33:06 - INFO    121:dbutils  - Database: C:\Users\mjpat\ft8ctl.sql
22:33:07 - INFO     79:_dxentity - Using DXCC cache C:\Users\mjpat\.local\cty
22:33:07 - INFO    155:dbutils  - Datebase Insert thread started
22:33:07 - INFO    235:dbutils  - Purge thread started (retry_time 15 minutes)
22:33:07 - INFO    199:ft8ctrl  - Call selector: DXCC100, POTA, Any
22:33:07 - INFO     80:base     - BlackList: KC5TT, KD7DPS, VA7QI, W5JDC...
22:33:07 - ERROR   211:ft8ctrl  - Call selector not found: "POTA"
"POTA" not found

I know you showed me the module and line to change but I have been searching all the files for POTA and can't find it. 
What file/line am I supposed to change to remove the POTA selector?

**Comment by 0x9900** [comment]
There is no plugin POTA. In the config file, in the section `ft8ctl` remove POTA from the `call_selector` field. 
If you want to chase POTA stations, use the plugin `Extra`.
In the latest version, the `ft8ctrl.yaml.sample`, you will find an example of how to use the Extra plugin.
